import { createElement } from '@lwc/engine-dom';
import Idbx_VotingWidget from 'c/idbx_VotingWidget';

describe('c-idbx-voting-widget', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-idbx-voting-widget', {
            is: Idbx_VotingWidget
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});