name: PR - Automerge

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge PR and post comment
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: "automerge"          # Only merge if PR has this label
          MERGE_REMOVE_LABELS: "automerge"  # Remove after merge
          MERGE_METHOD: merge
