name: PR - Build & SF Connect

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your main repo (the one with the workflow)
      - name: Checkout primary repo
        uses: actions/checkout@v4
        
  connect-to-envs:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        env: [QA, PROD]   # just environment names
    environment: ${{ matrix.env }}

    steps:
      - name: Install Salesforce CLI
        uses: patrykacc/sf-cli-setup@74431631871daefe43ea718c09a13977a407270f

      - name: Authenticate with Salesforce
        env:
          SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
        run: |
          echo "$SF_JWT_KEY" > server.key
          sf org login jwt \
            --client-id "$SF_CONSUMER_KEY" \
            --jwt-key-file server.key \
            --username "$SF_USERNAME" \
            --instance-url https://test.salesforce.com \
            --set-default

      - name: Verify connection
        run: sf org list
