name: PR - Build & SF Connect

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your main repo (the one with the workflow)
      - name: Checkout primary repo
        uses: actions/checkout@v4

      # Checkout the repo containing SfCliInstaller
      - name: Checkout SfCliInstaller repo
        uses: actions/checkout@v4
        with:
          repository: Sophos-2025-Grad-Hires/devops.actions
          path: devops-actions
          ref: main  # or whichever branch has the latest

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Build SfCliInstaller from the other repo
      - name: Build SfCliInstaller
        run: dotnet build devops-actions/tools/SfCliInstaller/SfCliInstaller/SfCliInstaller.csproj --configuration Release

      # Run SfCliInstaller (install latest CLI)
      - name: Run SfCliInstaller (install latest CLI)
        run: dotnet run --project devops-actions/tools/SfCliInstaller/SfCliInstaller/SfCliInstaller.csproj -- latest

      # Add the sf CLI to PATH
      - name: Add sf CLI to PATH
        run: echo "${HOME}/sf/bin" >> $GITHUB_PATH

      # Verify Salesforce CLI installation
      - name: Verify Salesforce CLI installation
        run: sf --version
        
  connect-to-ITAS019:
    runs-on: ubuntu-latest
    needs: build
    environment: ITAS019
    
    steps:
        - name: Write JWT private key
          run: echo "${{ secrets.SF_JWT_KEY }}" > server.key
  
        - name: Authenticate with Salesforce
          run: |
            sf org login jwt \
              --client-id ${{ secrets.SF_CONSUMER_KEY }} \
              --jwt-key-file server.key \
              --username ${{ secrets.SF_USERNAME }} \
              --instance-url https://test.salesforce.com \
  
        - name: Test org connection
          run: sf org display
          
  connect-to-ITAS029:
    runs-on: ubuntu-latest
    needs: build
    environment: ITAS029
    
    steps:
        - name: Write JWT private key
          run: echo "${{ secrets.SF_JWT_KEY }}" > server.key
  
        - name: Authenticate with Salesforce
          run: |
            sf org login jwt \
              --client-id ${{ secrets.SF_CONSUMER_KEY }} \
              --jwt-key-file server.key \
              --username ${{ secrets.SF_USERNAME }} \
              --instance-url https://test.salesforce.com \
  
        - name: Test org connection
          run: sf org display
