name: PR - Build & SF Connect

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your main repo (the one with the workflow)
      - name: Checkout primary repo
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        uses: patrykacc/sf-cli-setup@v1.1.0
        
  connect-to-ITAS019:
    runs-on: ubuntu-latest
    needs: build
    environment: ITAS019
    
    steps:
        - name: Write JWT private key
          run: echo "${{ secrets.SF_JWT_KEY }}" > server.key
  
        - name: Authenticate with Salesforce
          run: |
            sf org login jwt \
              --client-id ${{ secrets.SF_CONSUMER_KEY }} \
              --jwt-key-file server.key \
              --username ${{ secrets.SF_USERNAME }} \
              --instance-url https://test.salesforce.com \
  
        - name: Test org connection
          run: sf org display
          
  connect-to-ITAS029:
    runs-on: ubuntu-latest
    needs: build
    environment: ITAS029
    
    steps:
        - name: Write JWT private key
          run: echo "${{ secrets.SF_JWT_KEY }}" > server.key
  
        - name: Authenticate with Salesforce
          run: |
            sf org login jwt \
              --client-id ${{ secrets.SF_CONSUMER_KEY }} \
              --jwt-key-file server.key \
              --username ${{ secrets.SF_USERNAME }} \
              --instance-url https://test.salesforce.com \
  
        - name: Test org connection
          run: sf org display
